'use client'

import {useState} from 'react'
import {CTAButton} from '@/components/CTAButton'
import {ResourceLeadForm} from '@/components/leads/ResourceLeadForm'
import type {KnownLeadContext} from '@/lib/leads/contracts'
import type {UseCaseDocument} from '@/types/use-case'

const risks = [
  ['01', 'Approved version confusion', 'Find the canonical approved asset, its history, and its approval context.', 'approved-version-control'],
  ['02', 'Failed asset reproduction', 'Recover the prompts, models, references, settings, and decisions behind the work.', 'reproduce-ai-generated-assets'],
  ['03', 'Campaign variant sprawl', 'Connect every derivative to its approved source and intended delivery state.', 'ai-campaign-variant-control'],
  ['04', 'Wrong-spec production', 'Track channel, format, duration, market, and readiness requirements.', 'platform-spec-readiness'],
  ['05', 'Production handoff failure', 'Make context an organizational record instead of individual memory.', 'production-handoff-memory'],
  ['06', 'Unused creative waste', 'See what launched, what died, and what remains reusable.', 'unused-creative-asset-utilization'],
  ['07', 'Revision and scope-creep leakage', 'Trace notes, requests, decisions, branches, and the cost they created.', 'revision-scope-creep-cost'],
  ['08', 'Character and continuity drift', 'Preserve canonical references and history across scenes and production cycles.', 'character-continuity-governance'],
] as const

const faqs = [
  ['Is production memory another DAM?', 'No. Portals preserves the production context, lineage, decisions, and approvals that file storage and delivery systems often leave behind.'],
  ['Does Portals replace creative tools?', 'No. Teams keep using their generation, editing, review, storage, and delivery tools. Portals keeps the production record connected to the work.'],
  ['How is value proven?', 'A 21-day pilot applies Portals to one active workflow and one historical project, then measures recovery, reuse, handoffs, and rework.'],
]

function hrefForUseCase(useCases: UseCaseDocument[], slug: string) {
  return useCases.some((useCase) => useCase.slug === slug) ? `/use-cases/${slug}` : '/use-cases'
}

function Header() {
  return <header className="mx-auto flex w-full max-w-[1600px] items-center justify-between px-sms py-20 text-white"><a href="/" className="t-h3-sans !font-medium">portals</a><nav className="hidden gap-24 text-sm lowercase md:flex"><a href="/production-memory">production memory</a><a href="/use-cases">use cases</a><a href="/assessment">assess workflow</a></nav></header>
}

function FAQ() {
  const [open, setOpen] = useState<number | null>(null)
  return <section className="ui-grid py-fluid-[76,106] text-white"><div className="col-span-full mx-auto w-full max-w-4xl"><p className="t-p-sans mb-24 uppercase tracking-[.16em] text-white/45">questions</p>{faqs.map(([q, a], i) => <div key={q} className="border-t border-white/20"><button className="flex w-full items-center justify-between py-24 text-left t-p-lg-sans" onClick={() => setOpen(open === i ? null : i)} aria-expanded={open === i}>{q}<span>{open === i ? '−' : '+'}</span></button>{open === i && <p className="max-w-2xl pb-24 t-p-sans text-white/65">{a}</p>}</div>)}</div></section>
}

export function ProductionMemoryPage({context, useCases}: {context: KnownLeadContext; useCases: UseCaseDocument[]}) {
  return <><Header/><main className="text-white">
    <section className="ui-grid min-h-[78vh] items-center py-80"><div className="col-span-full max-w-6xl"><p className="t-p-sans mb-24 uppercase tracking-[.16em] text-white/45">the repository for AI-native production</p><h1 className="t-d1-sans max-w-5xl">Production Memory</h1><p className="t-p-lg-serif mt-32 max-w-3xl text-white/80">Preserve what made the work valuable.</p><p className="t-p-sans mt-24 max-w-2xl text-white/65">AI makes creative output abundant. Portals preserves the versions, context, decisions, and relationships behind the assets your team needs to understand, reproduce, extend, and reuse.</p><div className="mt-40 flex flex-wrap gap-16"><CTAButton href="/assessment" analyticsLabel="Assess Your Production Workflow" analyticsIntent="assessment">Assess Your Production Workflow</CTAButton><CTAButton href="/resources/production-memory-brief" appearance="plain" analyticsLabel="Download the Production Memory Brief" analyticsIntent="resource_download">Download the Production Memory Brief</CTAButton></div></div></section>
    <section className="ui-grid border-t border-white/15 py-fluid-[76,106]"><div className="col-span-full lg:col-span-5"><p className="t-p-sans uppercase tracking-[.16em] text-white/45">01 / definition</p><h2 className="t-d2-sans mt-24">What is production memory?</h2></div><div className="col-span-full mt-32 max-w-3xl lg:col-span-9 lg:mt-0"><p className="t-p-lg-serif text-white/85">Production memory is the complete, recoverable organizational record of how valuable creative work was made.</p><p className="t-p-sans mt-24 text-white/65">It connects an asset to versions, prompts, models, source references, settings, approvals, rejected directions, production decisions, derivatives, delivery status, and reuse opportunities. A finished asset tells you what shipped. Production memory tells you how it happened, why it changed, what it connects to, and how to build from it again.</p></div></section>
    <section className="ui-grid border-t border-white/15 py-fluid-[76,106]"><div className="col-span-full"><p className="t-p-sans uppercase tracking-[.16em] text-white/45">02 / value</p><div className="mt-24 grid gap-2 lg:grid-cols-2"><article className="bg-white/10 p-32"><h2 className="t-h2-sans">Stop losing production value</h2><p className="t-p-sans mt-20 max-w-xl text-white/65">Stop paying your team to rediscover work it already did. Recover the approved version, its context, decision history, lineage, and path to reproduce or extend it.</p></article><article className="bg-white/10 p-32"><h2 className="t-h2-sans">Turn prior work into future capacity</h2><p className="t-p-sans mt-20 max-w-xl text-white/65">When successful assets retain their production record, they become reusable systems: faster variants, consistent continuity, smoother handoffs, and less rework.</p></article></div></div></section>
    <section className="ui-grid border-t border-white/15 py-fluid-[76,106]"><div className="col-span-full lg:col-span-5"><p className="t-p-sans uppercase tracking-[.16em] text-white/45">03 / operating layer</p><h2 className="t-d2-sans mt-24">What Portals preserves</h2></div><div className="col-span-full mt-32 grid gap-x-24 gap-y-16 text-white/75 sm:grid-cols-2 lg:col-span-9 lg:mt-0">{['Approved asset identity','Complete version history','Prompts and model versions','Generation settings and source references','Rejected alternatives and decisions','Approval and contributor history','Parent and derivative relationships','Platform variants and handoff context'].map((item) => <div key={item} className="border-t border-white/20 pt-16 t-p-sans">{item}</div>)}</div></section>
    <section className="ui-grid border-t border-white/15 py-fluid-[76,106]"><div className="col-span-full"><p className="t-p-sans uppercase tracking-[.16em] text-white/45">04 / production risks</p><h2 className="t-d2-sans mt-24 max-w-4xl">The risks of fragmented context</h2><div className="mt-40 grid gap-px bg-white/15 sm:grid-cols-2 lg:grid-cols-4">{risks.map(([n, title, text, slug]) => <a href={hrefForUseCase(useCases, slug)} key={n} className="bg-white/5 p-24 transition-colors hover:bg-white/10"><span className="t-p-sans text-white/35">{n}</span><h3 className="t-h3-sans mt-48">{title}</h3><p className="t-p-sans mt-16 text-white/55">{text}</p></a>)}</div></div></section>
    <section className="ui-grid border-t border-white/15 py-fluid-[76,106]"><div className="col-span-full max-w-5xl"><p className="t-p-sans uppercase tracking-[.16em] text-white/45">05 / prove the value</p><h2 className="t-d2-sans mt-24">Production memory pays for itself when it becomes reusable capacity.</h2><p className="t-p-lg-serif mt-32 max-w-3xl text-white/75">A Portals Production Pilot applies Portals to one active workflow and one historical project, then measures whether a team can recover and reuse production memory faster than before.</p><div className="mt-40 flex flex-wrap gap-16"><CTAButton href="/assessment">Assess Your Production Workflow</CTAButton><CTAButton href="/pilot#scope" appearance="plain">Scope a Production Pilot</CTAButton></div></div></section>
    <section id="brief" className="ui-grid border-t border-white/15 py-fluid-[76,106]"><div className="col-span-full mx-auto w-full max-w-4xl"><p className="t-p-sans uppercase tracking-[.16em] text-white/45">06 / downloadable brief</p><h2 className="t-d2-sans mt-24">The Production Memory Brief</h2><p className="t-p-lg-serif mt-24 text-white/75">How AI-native creative teams preserve the versions, context, decisions, and relationships behind their most valuable work—and turn that memory into faster future production.</p><p className="t-p-sans mt-24 text-white/60">Built to be shared with production, creative operations, technical, executive, and agency stakeholders.</p><div className="mt-40"><ResourceLeadForm context={context} submissionType="guide_download" title="Download the Production Memory Brief" description="Get the framework, diagnostic worksheet, market evidence, and pilot criteria." interestLabel="which workflow is most relevant?" options={risks.map(([, title]) => ({value: title.toLowerCase().replaceAll(' ', '-'), label: title.toLowerCase()}))} downloadLabel="Download the Production Memory Brief" sourcePage="/production-memory"/></div></div></section>
    <FAQ/>
  </main></>
}

export function UseCasesHub({useCases}: {useCases: UseCaseDocument[]}) {
  return <><Header/><main className="ui-grid text-white"><section className="col-span-full min-h-[70vh] max-w-6xl py-80"><p className="t-p-sans tracking-[.16em]">production memory / use cases</p><h1 className="t-d1-sans mt-24 max-w-5xl">Where production memory pays for itself.</h1><p className="t-p-lg-serif mt-32 max-w-3xl text-white">Explore the operational moments where fragmented context becomes expensive—and where Portals helps teams recover, reuse, and compound creative work.</p><div className="mt-40 flex flex-wrap gap-16"><CTAButton href="/assessment">Assess Your Workflow</CTAButton><CTAButton href="/resources/production-memory-brief" appearance="plain">Download the Brief</CTAButton></div></section><section className="col-span-full py-fluid-[76,106]"><div className="grid gap-[2px] md:grid-cols-2">{useCases.map(({title, outcome, slug}, i) => <a key={slug} href={`/use-cases/${slug}`} className="bg-white/10 p-32 transition-colors hover:bg-white/10"><span className="t-p-sans text-white/35">{String(i+1).padStart(2,'0')}</span><h2 className="t-h3-sans mt-40">{title}</h2><p className="t-p-sans mt-16 text-white/60">{outcome}</p><span className="mt-32 inline-block t-p-sans underline underline-offset-4">read use case →</span></a>)}</div></section></main></>
}
