#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
PUBLISHER="${ROOT}/infra/lore/scripts/docker-buildx-lore-dockerhub.sh"
PROMOTER="${ROOT}/infra/pulumi/scripts/verify-and-promote-dockerhub-lore.sh"
RECORDER="${ROOT}/infra/pulumi/scripts/record-verified-dockerhub-lore.mjs"
RELEASE_WORKFLOW="${ROOT}/.github/workflows/lore-dockerhub-release.yml"
PROMOTION_WORKFLOW="${ROOT}/.github/workflows/lore-dockerhub-promote.yml"

grep -q 'REPOSITORY="${LORE_DOCKERHUB_REPOSITORY:-portalshq/lore}"' "${PUBLISHER}"
grep -q 'docker buildx build --platform linux/amd64' "${PUBLISHER}"
grep -q -- '--provenance=true --sbom=true --push' "${PUBLISHER}"
grep -q 'linux/amd64) : ;;' "${ROOT}/infra/lore/Dockerfile.loreserver.base"
grep -q 'linux/arm64) apt-get install -y gcc-aarch64-linux-gnu' "${ROOT}/infra/lore/Dockerfile.loreserver.base"
grep -q 'portalshq/lore@sha256' "${PROMOTER}"
grep -q -- '--certificate-oidc-issuer https://token.actions.githubusercontent.com' "${PROMOTER}"
grep -q 'for attempt in {1..6}; do' "${PROMOTER}"
grep -q 'run: cosign sign --yes "$IMAGE"' "${RELEASE_WORKFLOW}"
grep -q 'npm ci --prefix infra/pulumi --omit=dev --ignore-scripts' "${RELEASE_WORKFLOW}" "${PROMOTION_WORKFLOW}"
grep -q 'Commit verified deployment receipt' "${PROMOTION_WORKFLOW}"
! grep -q -- '--bundle' "${RELEASE_WORKFLOW}" "${PROMOTER}"
grep -q -- '--severity CRITICAL,HIGH --exit-code 1' "${PROMOTER}"
grep -q 'provenance does not bind build ID' "${PROMOTER}"
grep -q 'provenance does not bind base image' "${PROMOTER}"
grep -q 'atomicWriteJson(receiptsFile, ledger)' "${RECORDER}"
grep -q 'atomicWriteYaml(versionsFile, versions)' "${RECORDER}"
bash -n "${PUBLISHER}" "${PROMOTER}" "${BASH_SOURCE[0]}"
node --check "${RECORDER}"
