config:
  aws:region: us-east-1
  portals-platform:ed25519SigningKey:
    secure: AAABADhSXCBOavnp39ayIuqlyOrQpq6fO3C/3SOasOZZTgNybvo/rnsNAZZ/0IHmSG3Ynt+gNEKvn0XI2nJRHxOlRilvGSoPC5+S+A==
  docker:host: unix:///Users/vibrantceo/.orbstack/run/docker.sock
