config:
  aws:region: us-east-1
  portals-platform:ed25519SigningKey:
    secure: AAABADhSXCBOavnp39ayIuqlyOrQpq6fO3C/3SOasOZZTgNybvo/rnsNAZZ/0IHmSG3Ynt+gNEKvn0XI2nJRHxOlRilvGSoPC5+S+A==
  portals-platform:databaseInstanceClass: db.t4g.micro
  portals-platform:databaseAllocatedStorage: "20"
  portals-platform:databaseVersion: "15.18"
