config:
  portals-platform:environment: prod
  portals-platform:vpcCidr: 10.1.0.0/16
  portals-platform:publicSubnetCidrs: 10.1.1.0/24,10.1.2.0/24,10.1.3.0/24
  portals-platform:privateSubnetCidrs: 10.1.10.0/24,10.1.11.0/24,10.1.12.0/24
  portals-platform:publicIngressEnabled: "false"
  portals-platform:loreServiceDesiredCount: "0"
  portals-platform:controlPlaneDesiredCount: "0"
  portals-platform:authGatewayDesiredCount: "0"
  portals-platform:authFoundationEnabled: "true"
  portals-platform:securityControlsEnabled: "true"
  portals-platform:recoveryControlsEnabled: "true"
  portals-platform:lowCostRdsSnapshotsEnabled: "true"
  aws:region: us-east-1
  portals-platform:databaseBackupRetentionDays: "1"
  portals-platform:databaseInstanceClass: db.t4g.micro
  portals-platform:databaseAllocatedStorage: "20"
  portals-platform:databaseVersion: "15.18"
