config:
  aws:region: us-east-1
  portals-platform:databaseInstanceClass: db.t4g.micro
  portals-platform:databaseAllocatedStorage: "20"
  portals-platform:databaseVersion: "15.18"
  portals-platform:loreServiceDesiredCount: "0"
  portals-platform:controlPlaneDesiredCount: "0"
  portals-platform:authGatewayDesiredCount: "1"
  portals-platform:ecsLaunchType: EC2
  portals-platform:memoryMonitoringEnabled: "true"
  portals-platform:loreCpuArchitecture: X86_64
  portals-platform:authGatewayCpuArchitecture: X86_64
  portals-platform:backendApiPublicEnabled: "false"
  portals-platform:backendServiceDesiredCount: "0"
  portals-platform:emailServiceEnabled: "false"
  portals-platform:authFoundationEnabled: "true"
  portals-platform:publicIngressEnabled: "false"
  portals-platform:jwksPublicationEnabled: "false"
  portals-platform:recoveryControlsEnabled: "true"
  portals-platform:databaseBackupRetentionDays: "1"
  portals-platform:lowCostRdsSnapshotsEnabled: "true"
  portals-platform:manualSnapshotRetentionCount: "7"
  portals-platform:ecsCpuArchitecture: ARM64
  portals-platform:threatDetectionEnabled: "false"
  portals-platform:securityReviewDate: ""
  portals-platform:authDomainPrefix: portals-dev-auth-907199504810
  portals-platform:authCallbackUrls: https://auth.portals.works/callback
  portals-platform:authLogoutUrls: https://auth.portals.works/logout
  portals-platform:authHostname: auth.portals.works
  portals-platform:loreHostname: lore.portals.works
  portals-platform:loreJwksEndpoint: https://auth.portals.works/.well-known/jwks.json
  portals-platform:loreJwtIssuer: https://auth.portals.works
  portals-platform:jwtSigningEnabled: "false"
  portals-platform:credentialRotationEpoch: 2026-08-10-lore-security-rollout-v2
  portals-platform:securityControlsEnabled: "true"
  portals-platform:publicCertificateArn: arn:aws:acm:us-east-1:907199504810:certificate/32f56a6f-6348-4573-8df1-c930b5acedb6
  portals-platform:alarmNotificationEndpoint: eng@portals.works
