use axum::body::Body;
use axum::http::{Request, StatusCode};
use http_body_util::BodyExt;
use std::sync::Arc;
use tower::util::ServiceExt;

/// Build a test Router backed by a real Postgres database.
/// Uses sqlx::test which creates a temporary database per test.
fn test_app(pool: sqlx::PgPool) -> axum::Router {
    let store = Arc::new(persistence::PostgresStateStore::new(pool));
    let (_, signing_key_b64) = api::auth::DataPlaneSigningKey::generate();
    let signing_key = api::auth::DataPlaneSigningKey::from_env(&signing_key_b64)
        .expect("failed to create signing key from generated bytes");

    let state = api::http::AppState {
        store,
        signing_key,
        dp_token_expiry_secs: 3600,
    };

    api::http::build_router(state, false, false, None)
}

// ============================================================
// Health
// ============================================================

#[sqlx::test(migrations = "../persistence/migrations")]
#[ignore] // requires running Postgres: docker compose up postgres
async fn healthz_returns_200(pool: sqlx::PgPool) {
    let app = test_app(pool);
    let response = app
        .oneshot(
            Request::builder()
                .uri("/healthz")
                .body(Body::empty())
                .unwrap(),
        )
        .await
        .unwrap();
    assert_eq!(response.status(), StatusCode::OK);
}

#[sqlx::test(migrations = "../persistence/migrations")]
#[ignore]
async fn readyz_returns_200(pool: sqlx::PgPool) {
    let app = test_app(pool);
    let response = app
        .oneshot(
            Request::builder()
                .uri("/readyz")
                .body(Body::empty())
                .unwrap(),
        )
        .await
        .unwrap();
    assert_eq!(response.status(), StatusCode::OK);
}

// ============================================================
// Repository CRUD
// ============================================================

#[sqlx::test(migrations = "../persistence/migrations")]
#[ignore]
async fn create_repository_returns_201(pool: sqlx::PgPool) {
    let app = test_app(pool);
    let response = app
        .oneshot(
            Request::builder()
                .method("POST")
                .uri("/api/v1/repositories")
                .header("content-type", "application/json")
                .body(Body::from(
                    serde_json::to_vec(&serde_json::json!({
                        "name": "test-repo",
                        "storage_tier": "standard"
                    }))
                    .unwrap(),
                ))
                .unwrap(),
        )
        .await
        .unwrap();
    assert_eq!(response.status(), StatusCode::CREATED);

    let body = response.into_body().collect().await.unwrap().to_bytes();
    let json: serde_json::Value = serde_json::from_slice(&body).unwrap();
    assert_eq!(json["name"], "test-repo");
    assert_eq!(json["storage_tier"], "standard");
    assert!(json["id"].as_str().unwrap().starts_with("repo-"));
    assert_eq!(json["version"], 1);
}

#[sqlx::test(migrations = "../persistence/migrations")]
#[ignore]
async fn create_repository_empty_name_returns_400(pool: sqlx::PgPool) {
    let app = test_app(pool);
    let response = app
        .oneshot(
            Request::builder()
                .method("POST")
                .uri("/api/v1/repositories")
                .header("content-type", "application/json")
                .body(Body::from(
                    serde_json::to_vec(&serde_json::json!({
                        "name": ""
                    }))
                    .unwrap(),
                ))
                .unwrap(),
        )
        .await
        .unwrap();
    assert_eq!(response.status(), StatusCode::BAD_REQUEST);
}

#[sqlx::test(migrations = "../persistence/migrations")]
#[ignore]
async fn list_repositories_returns_empty_array(pool: sqlx::PgPool) {
    let app = test_app(pool);
    let response = app
        .oneshot(
            Request::builder()
                .uri("/api/v1/repositories")
                .body(Body::empty())
                .unwrap(),
        )
        .await
        .unwrap();
    assert_eq!(response.status(), StatusCode::OK);

    let body = response.into_body().collect().await.unwrap().to_bytes();
    let json: serde_json::Value = serde_json::from_slice(&body).unwrap();
    assert!(json.is_array());
    assert_eq!(json.as_array().unwrap().len(), 0);
}

#[sqlx::test(migrations = "../persistence/migrations")]
#[ignore]
async fn get_nonexistent_repository_returns_404(pool: sqlx::PgPool) {
    let app = test_app(pool);
    let response = app
        .oneshot(
            Request::builder()
                .uri("/api/v1/repositories/repo-does-not-exist")
                .body(Body::empty())
                .unwrap(),
        )
        .await
        .unwrap();
    assert_eq!(response.status(), StatusCode::NOT_FOUND);
}

// ============================================================
// Organization CRUD
// ============================================================

#[sqlx::test(migrations = "../persistence/migrations")]
#[ignore]
async fn create_organization_returns_201(pool: sqlx::PgPool) {
    let app = test_app(pool);
    let response = app
        .oneshot(
            Request::builder()
                .method("POST")
                .uri("/api/v1/organizations")
                .header("content-type", "application/json")
                .body(Body::from(
                    serde_json::to_vec(&serde_json::json!({
                        "name": "Test Org",
                        "slug": "test-org"
                    }))
                    .unwrap(),
                ))
                .unwrap(),
        )
        .await
        .unwrap();
    assert_eq!(response.status(), StatusCode::CREATED);

    let body = response.into_body().collect().await.unwrap().to_bytes();
    let json: serde_json::Value = serde_json::from_slice(&body).unwrap();
    assert_eq!(json["name"], "Test Org");
    assert_eq!(json["slug"], "test-org");
}

#[sqlx::test(migrations = "../persistence/migrations")]
#[ignore]
async fn list_organizations_returns_empty_array(pool: sqlx::PgPool) {
    let app = test_app(pool);
    let response = app
        .oneshot(
            Request::builder()
                .uri("/api/v1/organizations")
                .body(Body::empty())
                .unwrap(),
        )
        .await
        .unwrap();
    assert_eq!(response.status(), StatusCode::OK);

    let body = response.into_body().collect().await.unwrap().to_bytes();
    let json: serde_json::Value = serde_json::from_slice(&body).unwrap();
    assert!(json.is_array());
}

// ============================================================
// 404 fallback
// ============================================================

#[sqlx::test(migrations = "../persistence/migrations")]
#[ignore]
async fn unknown_route_returns_404(pool: sqlx::PgPool) {
    let app = test_app(pool);
    let response = app
        .oneshot(
            Request::builder()
                .uri("/api/v1/nonexistent")
                .body(Body::empty())
                .unwrap(),
        )
        .await
        .unwrap();
    assert_eq!(response.status(), StatusCode::NOT_FOUND);
}

// ============================================================
// Request ID middleware
// ============================================================

#[sqlx::test(migrations = "../persistence/migrations")]
#[ignore]
async fn response_includes_request_id_header(pool: sqlx::PgPool) {
    let app = test_app(pool);
    let response = app
        .oneshot(
            Request::builder()
                .uri("/healthz")
                .body(Body::empty())
                .unwrap(),
        )
        .await
        .unwrap();
    let request_id = response.headers().get("x-request-id");
    assert!(
        request_id.is_some(),
        "x-request-id header should be present"
    );
    let val = request_id.unwrap().to_str().unwrap();
    assert!(!val.is_empty());
}

// ============================================================
// JWT Authentication
// ============================================================

#[sqlx::test(migrations = "../persistence/migrations")]
#[ignore]
async fn jwt_auth_rejects_missing_token(pool: sqlx::PgPool) {
    let store = Arc::new(persistence::PostgresStateStore::new(pool));
    let (_, signing_key_b64) = api::auth::DataPlaneSigningKey::generate();
    let signing_key = api::auth::DataPlaneSigningKey::from_env(&signing_key_b64)
        .expect("failed to create signing key from generated bytes");

    let state = api::http::AppState {
        store,
        signing_key,
        dp_token_expiry_secs: 3600,
    };

    // Enable JWT auth
    let app = api::http::build_router(state, true, false, None);

    let response = app
        .oneshot(
            Request::builder()
                .uri("/api/v1/repositories")
                .body(Body::empty())
                .unwrap(),
        )
        .await
        .unwrap();
    assert_eq!(response.status(), StatusCode::UNAUTHORIZED);
}

#[sqlx::test(migrations = "../persistence/migrations")]
#[ignore]
async fn jwt_auth_rejects_invalid_token(pool: sqlx::PgPool) {
    let store = Arc::new(persistence::PostgresStateStore::new(pool));
    let (_, signing_key_b64) = api::auth::DataPlaneSigningKey::generate();
    let signing_key = api::auth::DataPlaneSigningKey::from_env(&signing_key_b64)
        .expect("failed to create signing key from generated bytes");

    let state = api::http::AppState {
        store,
        signing_key,
        dp_token_expiry_secs: 3600,
    };

    // Enable JWT auth
    let app = api::http::build_router(state, true, false, None);

    let response = app
        .oneshot(
            Request::builder()
                .uri("/api/v1/repositories")
                .header("authorization", "Bearer invalid-token")
                .body(Body::empty())
                .unwrap(),
        )
        .await
        .unwrap();
    assert_eq!(response.status(), StatusCode::UNAUTHORIZED);
}

#[sqlx::test(migrations = "../persistence/migrations")]
#[ignore]
async fn jwt_auth_allows_valid_token(pool: sqlx::PgPool) {
    let store = Arc::new(persistence::PostgresStateStore::new(pool));
    let (_, signing_key_b64) = api::auth::DataPlaneSigningKey::generate();
    let signing_key = api::auth::DataPlaneSigningKey::from_env(&signing_key_b64)
        .expect("failed to create signing key from generated bytes");

    let state = api::http::AppState {
        store,
        signing_key: signing_key.clone(),
        dp_token_expiry_secs: 3600,
    };

    // Enable JWT auth
    let app = api::http::build_router(state, true, false, None);

    // Generate a valid token
    let token = signing_key
        .issue_data_plane_token("test@example.com", "repo-123", vec!["ReadChunks".to_string()], 3600)
        .expect("failed to issue token");

    let response = app
        .oneshot(
            Request::builder()
                .uri("/api/v1/repositories")
                .header("authorization", format!("Bearer {}", token))
                .body(Body::empty())
                .unwrap(),
        )
        .await
        .unwrap();
    assert_eq!(response.status(), StatusCode::OK);
}

// ============================================================
// Idempotency Keys
// ============================================================

#[sqlx::test(migrations = "../persistence/migrations")]
#[ignore]
async fn idempotency_caches_successful_response(pool: sqlx::PgPool) {
    let store = Arc::new(persistence::PostgresStateStore::new(pool));
    let (_, signing_key_b64) = api::auth::DataPlaneSigningKey::generate();
    let signing_key = api::auth::DataPlaneSigningKey::from_env(&signing_key_b64)
        .expect("failed to create signing key from generated bytes");

    let state = api::http::AppState {
        store,
        signing_key,
        dp_token_expiry_secs: 3600,
    };

    // Enable idempotency
    let app = api::http::build_router(state, false, true, None);

    let idempotency_key = "test-key-123";

    // First request
    let response1 = app
        .clone()
        .oneshot(
            Request::builder()
                .method("POST")
                .uri("/api/v1/organizations")
                .header("content-type", "application/json")
                .header("idempotency-key", idempotency_key)
                .body(Body::from(
                    serde_json::to_vec(&serde_json::json!({
                        "name": "Test Org",
                        "slug": "test-org"
                    }))
                    .unwrap(),
                ))
                .unwrap(),
        )
        .await
        .unwrap();
    assert_eq!(response1.status(), StatusCode::CREATED);

    let body1 = response1.into_body().collect().await.unwrap().to_bytes();
    let json1: serde_json::Value = serde_json::from_slice(&body1).unwrap();
    let id1 = json1["id"].as_str().unwrap();

    // Second request with same idempotency key
    let response2 = app
        .oneshot(
            Request::builder()
                .method("POST")
                .uri("/api/v1/organizations")
                .header("content-type", "application/json")
                .header("idempotency-key", idempotency_key)
                .body(Body::from(
                    serde_json::to_vec(&serde_json::json!({
                        "name": "Different Org",
                        "slug": "different-org"
                    }))
                    .unwrap(),
                ))
                .unwrap(),
        )
        .await
        .unwrap();
    assert_eq!(response2.status(), StatusCode::CREATED);

    let body2 = response2.into_body().collect().await.unwrap().to_bytes();
    let json2: serde_json::Value = serde_json::from_slice(&body2).unwrap();
    let id2 = json2["id"].as_str().unwrap();

    // Should return the same ID (cached response)
    assert_eq!(id1, id2);
    assert_eq!(json2["name"], "Test Org"); // Original name, not "Different Org"
}

// ============================================================
// Organization Soft-Delete
// ============================================================

#[sqlx::test(migrations = "../persistence/migrations")]
#[ignore]
async fn organization_soft_delete_returns_202(pool: sqlx::PgPool) {
    let app = test_app(pool);
    
    // Create organization
    let create_response = app
        .clone()
        .oneshot(
            Request::builder()
                .method("POST")
                .uri("/api/v1/organizations")
                .header("content-type", "application/json")
                .body(Body::from(
                    serde_json::to_vec(&serde_json::json!({
                        "name": "Test Org",
                        "slug": "test-org"
                    }))
                    .unwrap(),
                ))
                .unwrap(),
        )
        .await
        .unwrap();
    assert_eq!(create_response.status(), StatusCode::CREATED);

    let body = create_response.into_body().collect().await.unwrap().to_bytes();
    let json: serde_json::Value = serde_json::from_slice(&body).unwrap();
    let org_id = json["id"].as_str().unwrap();

    // Delete organization (soft delete)
    let delete_response = app
        .oneshot(
            Request::builder()
                .method("DELETE")
                .uri(&format!("/api/v1/organizations/{}", org_id))
                .body(Body::empty())
                .unwrap(),
        )
        .await
        .unwrap();
    assert_eq!(delete_response.status(), StatusCode::ACCEPTED);
}

#[sqlx::test(migrations = "../persistence/migrations")]
#[ignore]
async fn organization_with_repositories_cannot_delete(pool: sqlx::PgPool) {
    let app = test_app(pool);
    
    // Create organization
    let create_org_response = app
        .clone()
        .oneshot(
            Request::builder()
                .method("POST")
                .uri("/api/v1/organizations")
                .header("content-type", "application/json")
                .body(Body::from(
                    serde_json::to_vec(&serde_json::json!({
                        "name": "Test Org",
                        "slug": "test-org"
                    }))
                    .unwrap(),
                ))
                .unwrap(),
        )
        .await
        .unwrap();
    assert_eq!(create_org_response.status(), StatusCode::CREATED);

    let org_body = create_org_response.into_body().collect().await.unwrap().to_bytes();
    let org_json: serde_json::Value = serde_json::from_slice(&org_body).unwrap();
    let org_id = org_json["id"].as_str().unwrap();

    // Create repository in organization
    let create_repo_response = app
        .clone()
        .oneshot(
            Request::builder()
                .method("POST")
                .uri("/api/v1/repositories")
                .header("content-type", "application/json")
                .body(Body::from(
                    serde_json::to_vec(&serde_json::json!({
                        "name": "test-repo",
                        "storage_tier": "standard",
                        "organization": org_id
                    }))
                    .unwrap(),
                ))
                .unwrap(),
        )
        .await
        .unwrap();
    assert_eq!(create_repo_response.status(), StatusCode::CREATED);

    // Try to delete organization (should fail due to active repository)
    let delete_response = app
        .oneshot(
            Request::builder()
                .method("DELETE")
                .uri(&format!("/api/v1/organizations/{}", org_id))
                .body(Body::empty())
                .unwrap(),
        )
        .await
        .unwrap();
    // Should return 202 (accepted for deletion) but the reconciler will fail to finalize
    // This is expected behavior - the deletion is accepted but will fail during finalization
    assert_eq!(delete_response.status(), StatusCode::ACCEPTED);
}
