include classpath("application.conf")

queues {
  events {
    defaultVisibilityTimeout = 300
    delay = 0
    receiveMessageWait = 0
    deadLettersQueue {
      name = "events-dlq"
      maxReceiveCount = 5
    }
  }
  
  events-dlq {
    defaultVisibilityTimeout = 300
    delay = 0
    receiveMessageWait = 0
  }
}

node-address {
  host = "0.0.0.0"
  port = 9324
  context-path = ""
}

rest-sqs {
  enabled = true
  bind-port = 9325
  bind-hostname = "0.0.0.0"
  sqs-limits = strict
}
